# syntax = docker/dockerfile:1

# Make sure RUBY_VERSION matches the Ruby version in .ruby-version and Gemfile
ARG RUBY_VERSION=3.4.7

# ----------------------- Base -----------------------
FROM registry.docker.com/library/ruby:$RUBY_VERSION-alpine as base

ARG ARG_RAILS_MASTER_KEY
ARG ARG_RAILS_ENV=development
ARG ARG_BUNDLE_WITHOUT=""

ENV APP_HOME_PATH="/url_shorter" \
  RAILS_ENV=${ARG_RAILS_ENV} \
  BUNDLE_WITHOUT=${ARG_BUNDLE_WITHOUT} \
  RAILS_MASTER_KEY=${ARG_RAILS_MASTER_KEY} \
  BUNDLE_PATH="/usr/local/bundle"

WORKDIR ${APP_HOME_PATH}

# ----------------------- Build -----------------------
FROM base as build

# Install packages needed to build gems
# Use virtual build-dependency tag so we can remove these packages after bundle install
RUN apk update \
  && apk add --update --no-cache --virtual build-dependency make gcc g++ musl-dev yaml-dev postgresql-dev

# Install application gems
COPY ./Gemfile* ${APP_HOME_PATH}/
RUN gem install bundler -v $(cat Gemfile.lock | tail -1 | tr -d " ") \
  && bundle install --no-cache --jobs 2 --retry 5 \
  && bundle clean --force \
  && rm -rf ~/.bundle/ "${BUNDLE_PATH}"/ruby/*/cache "${BUNDLE_PATH}"/ruby/*/bundler/gems/*/.git \
  && bundle exec bootsnap precompile --gemfile

# Remove build dependencies
RUN apk del build-dependency

# ----------------------- After Build -----------------------
FROM base as after_build

# Copy built artifacts: gems, application
COPY --from=build ${BUNDLE_PATH} ${BUNDLE_PATH}

# Install runtime dependencies
RUN apk add --update --no-cache libpq tzdata

EXPOSE 3000

# ----------------------- Development -----------------------
FROM after_build as development

ENTRYPOINT ["./docker/entrypoint-development.sh"]

CMD ["bundle", "exec", "rails", "server", "-p", "3000", "-b", "0.0.0.0"]
